[package]
name = "iced_aw"
version = "0.1.0"
authors = ["Kaiden42 <gitlab@tinysn.com>"]
edition = "2018"
description = "Additional widgets for the Iced GUI library"
license = "MIT"
repository = "https://github.com/kaiden42/iced_aw"
# TODO documentation
readme = "README.md"
keywords = ["gui", "ui", "graphics", "interface", "widgets", "iced"]
categories = ["gui"]

[features]
badge = []
button = []
card = []
colors = []
date_picker = ["chrono", "lazy_static", "icon_text"]
color_picker = ["icon_text", "iced_graphics/canvas"]
floating_button = ["button"]
grid = []
glow = [] # TODO
icon_text = []
icons = []
modal = []
tab_bar = []
tabs = ["tab_bar"]
time_picker = ["chrono", "icon_text", "iced_graphics/canvas"]
wrap = []
number_input = ["num-traits"]


default = [
    "badge",
    "card",
    "colors",
    "date_picker",
    "color_picker",
    "floating_button",
    "grid",
    "modal",
    "tab_bar",
    "tabs",
    "time_picker",
    "wrap"
]

[dependencies]
num-traits = { version = "0.2.14", optional = true }
iced_style = { git = "https://github.com/yusdacra/iced.git", rev = "97ea2687c42beee2100dc11a2f344e5d7a554e2b" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iced_native = { git = "https://github.com/yusdacra/iced.git", rev = "97ea2687c42beee2100dc11a2f344e5d7a554e2b" }
iced_graphics = { git = "https://github.com/yusdacra/iced.git", rev = "97ea2687c42beee2100dc11a2f344e5d7a554e2b" }
chrono = { version = "0.4.19", optional = true }
lazy_static = { version = "1.4.0", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced_web = { git = "https://github.com/yusdacra/iced.git", rev = "97ea2687c42beee2100dc11a2f344e5d7a554e2b" }
dodrio = "0.2.0"
wasm-bindgen = "0.2.69"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.46"

[workspace]
members = [
    # "examples/badge",
    # "examples/card",
    # "examples/color_picker",
    # "examples/date_picker",
    # "examples/floating_button",
    # "examples/modal",
    #"examples/tab_bar",
    #"examples/tabs",
    #"examples/tabs_min",
    # "examples/time_picker",
    # "examples/web"
]
